### ISSUE TITLE
Dijagram sakvenci

### ISSUE THREAD

**Issue by ibecir** [bmasovic1/ooad-2022-2023-ToyStore#21]
1. Ne valja protok informacija, korisnik zatrazi pregled svega, nakon toga opcionalno klinke na jedan artikal i dobije info o njemu
2. Validacija podataka na pogresnom mjestu je <<alt>> fragment
3. Alternativno ne mora ici na korpu svaki put kad doda proizvod u korpu

**Comment by ibecir** [comment]
Nije popravljen dijagram sekvenci

**Comment by bmasovic1** [comment]
> Nije popravljen dijagram sekvenci

Popravljen

**Comment by ibecir** [comment]
Validacija podataka nije moguca bez unosa podataka, stavite prije alt segmenta unos podataka a onda system vrsi validaciju i postupa na osnovu rezultata.
