### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ibecir** [bmasovic1/ooad-2022-2023-ToyStore#24]
1. Za strukturalne patterne dodati i klasni dijagram za one patterne koje cete implementirati u sistemu kako bismo imali jasnu sliku i na vrijeme vidjeli da li ce se pattern dobro implementirati.
2. Za kreacijske patterne dodati i klasni dijagram za one patterne koje cete implementirati u sistemu kako bismo imali jasnu sliku i na vrijeme vidjeli da li ce se pattern dobro implementirati.
3. ER dijagram trebamo exportovati is SQL management studia kako bismo imali pravo stanje baze, Korisnik je AspNetUser, sad vise ne crtamo dijagrame nego pokazujemo stvarno stanje tabela iz baze a na osnovu nasih klasa

**Comment by bmasovic1** [comment]
> 1. Za strukturalne patterne dodati i klasni dijagram za one patterne koje cete implementirati u sistemu kako bismo imali jasnu sliku i na vrijeme vidjeli da li ce se pattern dobro implementirati.
> 2. Za kreacijske patterne dodati i klasni dijagram za one patterne koje cete implementirati u sistemu kako bismo imali jasnu sliku i na vrijeme vidjeli da li ce se pattern dobro implementirati.
> 3. ER dijagram trebamo exportovati is SQL management studia kako bismo imali pravo stanje baze, Korisnik je AspNetUser, sad vise ne crtamo dijagrame nego pokazujemo stvarno stanje tabela iz baze a na osnovu nasih klasa

Popravljeno @ibecir
