### ISSUE TITLE
Refaktoring

### ISSUE THREAD

**Issue by Azra1802** [bmasovic1/ooad-2022-2023-ToyStore#31]
### Također onemogućiti editovanje istog.
 @hapiiiii @bmasovic1

**Comment by bmasovic1** [comment]
> ### Unutar klase Kartica za atribut BrojKartice popraviti validaciju kako bi bila jasnija.
> ### Atribut Datum: DateTime za klase Narudzba, Feedback, Naplata prepraviti tako da se oni prilikom kreiranja automatksi postavljaju trenutnim datumom i vremenom, jer nema smisla da se može postaviti neki budici ili prosli datum i vrijeme.
> ### Također onemogućiti editovanje istog.
> @hapiiiii @bmasovic1

@Azra1802 popravljeno
